### ISSUE TITLE
函数或变量 'match_results' 无法识别。  出错 MethodEvaluation (第 82 行) match_results=tril(match_results,-frame_rate*time_constant);你好，我在运行程序是出现了以上报错，请问需要如何修改呢

### ISSUE THREAD

**Issue by iuujing** [KN-Zhang/loop-closure-detection-evaluation-codes#1]

**Comment by KN-Zhang** [comment]
请问解决了吗？

**Comment by KN-Zhang** [comment]
> _No description provided._

请问解决了吗

**Comment by iuujing** [comment]
感谢作者回复，已经解决了



---- 回复的原邮件 ----
| 发件人 | Kaining ***@***.***> |
| 日期 | 2024年07月31日 18:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [KN-Zhang/loop-closure-detection-evaluation-codes] 函数或变量 'match_results' 无法识别。  出错 MethodEvaluation (第 82 行) match_results=tril(match_results,-frame_rate*time_constant);你好，我在运行程序是出现了以上报错，请问需要如何修改呢 (Issue #1) |

No description provided.

请问解决了吗
